### ISSUE TITLE
「一入 Java 深似海 」第四节课的冒泡排序有错误

### ISSUE THREAD

**Issue by jayrwin** [mercyblitz/segmentfault-lessons#10]
输入： of(5,7,6,8,1,2);
期望结果:  [1, 2, 5, 6, 7, 8]
实际结果：[1, 6, 5, 7, 2, 8]
链接:
https://github.com/mercyblitz/segmentfault-lessons/blob/master/%E3%80%8C%E4%B8%80%E5%85%A5%20Java%20%E6%B7%B1%E4%BC%BC%E6%B5%B7%20%E3%80%8D/%E4%BB%A3%E7%A0%81/segmentfault/deep-in-java/stage-2/lesson-4/src/main/java/com/segmentfault/deep/in/java/collection/algorithm/BubbleSort.java

**Comment by jayrwin** [comment]
示例参数：[3,1,2,5,4] 是能够正常工作滴

**Comment by mercyblitz** [comment]
该问题已被小伙伴 PR修复~
